CREATE TABLE `device` (
  `guid` varchar(5) NOT NULL,
  `device_type` varchar(5) NOT NULL,
  `price` varchar(8) NOT NULL,
  `device_version` varchar(8) NOT NULL,
  `bought_date` date DEFAULT NULL,
  `leading_official` varchar(5) DEFAULT NULL,
  `production_date` date DEFAULT NULL,
  `phone_number` varchar(15) NOT NULL,
  `yearly_inspection_status` varchar(5) NOT NULL,
  `quaterly_inspection_date` date DEFAULT NULL,
  `monthly_inspection_date` date DEFAULT NULL,
  `manufacturer` varchar(8) NOT NULL,
  `is_rebuild_device` varchar(8) NOT NULL,
  `maintenance_period` date NOT NULL,
  `plan_scrap_date` date DEFAULT NULL,
  `using_unit` varchar(8) DEFAULT NULL,
  `device_status` varchar(8) DEFAULT NULL,
  `start_use_date` date DEFAULT NULL,
  `remark` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `workareainfo` (
  `guid` varchar(40) NOT NULL,
  `id` varchar(15) NOT NULL,
  `inspection_area_name` varchar(5) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='工区信息'CREATE TABLE `jobinfo` (
  `guid` varchar(5) NOT NULL,
  `unit_id` varchar(5) NOT NULL,
  `line_id` varchar(4) NOT NULL,
  `track_division` varchar(5) NOT NULL,
  `work_area_id` varchar(5) NOT NULL,
  `line_name` varchar(10) NOT NULL,
  `line_direction` varchar(2) DEFAULT NULL,
  `track_id` varchar(12) DEFAULT NULL,
  `station_id` varchar(7) DEFAULT NULL,
  `turnout_id` varchar(16) DEFAULT NULL,
  `weld_line_id` varchar(20) DEFAULT NULL,
  `mileage` double(10,5) NOT NULL,
  `left_right_track` varchar(2) NOT NULL,
  `entering_date` date NOT NULL,
  `entering_person` varchar(20) NOT NULL,
  `device_id` varchar(5) NOT NULL,
  `slight_wound_number` int(5) NOT NULL,
  `severe_wound_number` int(5) NOT NULL,
  `task_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`guid`),
  KEY `line_id` (`line_id`),
  KEY `work_area_id` (`work_area_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `lineareainfo` (
  `guid` varchar(40) NOT NULL,
  `id` varchar(15) NOT NULL,
  `line_area_name` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线路工区信息'CREATE TABLE `lineinfo` (
  `guid` varchar(40) NOT NULL,
  `id` varchar(4) NOT NULL COMMENT '线路信息',
  `line_name` varchar(5) NOT NULL,
  `line_direction` varchar(2) NOT NULL,
  `start_mileage` double(10,5) DEFAULT NULL,
  `end_mileage` double(10,5) DEFAULT NULL,
  `extension_length` double(10,5) DEFAULT NULL,
  `rail_laying_date` date DEFAULT NULL,
  `rail_type` varchar(6) DEFAULT NULL,
  `pre_year_pass_weight` double(10,0) DEFAULT NULL,
  `min_yearly_inspection_number` int(5) NOT NULL,
  `find_severe_wound` int(5) NOT NULL,
  `existing_wound_number` int(5) NOT NULL,
  `wound_rate` double(5,2) NOT NULL,
  `current_rail_status_evaluate` varchar(15) NOT NULL,
  `yearly_inspection_number` int(5) NOT NULL,
  `inspection_area_insp_block_number` int(5) NOT NULL,
  `responsible_inspeciton_area` varchar(5) NOT NULL COMMENT '负责探伤工区',
  `remark` varchar(100) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线路信息\r\n'CREATE TABLE `person` (
  `guid` varchar(5) NOT NULL,
  `password` varchar(20) NOT NULL,
  `work_id` varchar(5) DEFAULT NULL,
  `name` varchar(5) NOT NULL,
  `identity_card_id` varchar(18) NOT NULL,
  `literacy` varchar(5) NOT NULL,
  `team_id` varchar(8) DEFAULT NULL,
  `birthday` date NOT NULL,
  `phone_number` varchar(15) NOT NULL,
  `entering_date` date NOT NULL,
  `entering_person` varchar(5) NOT NULL,
  `entering_person_phone_number` varchar(15) NOT NULL,
  `find_slight_wound` int(5) NOT NULL,
  `find_severe_wound` int(5) NOT NULL,
  `team` varchar(5) DEFAULT NULL,
  `department_id` varchar(5) DEFAULT NULL,
  `sex` varchar(2) DEFAULT NULL,
  `job` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='人员信息'CREATE TABLE `trackdivisioninfo` (
  `guid` varchar(40) NOT NULL,
  `id` varchar(15) NOT NULL,
  `track_division_name` varchar(5) NOT NULL,
  `line_id` varchar(4) NOT NULL,
  `line_name` varchar(5) NOT NULL,
  `line_direction` varchar(2) NOT NULL,
  `start_mileage` double(10,5) DEFAULT NULL,
  `end_mileage` double(10,5) DEFAULT NULL,
  `extension_length` double(10,5) DEFAULT NULL,
  `rail_laying_date` date DEFAULT NULL,
  `rail_type` varchar(6) DEFAULT NULL,
  `pre_year_pass_weight` double(10,0) DEFAULT NULL,
  `min_yearly_inspection_number` int(5) NOT NULL,
  `find_severe_wound` int(5) NOT NULL,
  `existing_wound_number` int(5) NOT NULL,
  `wound_rate` double(5,2) NOT NULL,
  `current_rail_status_evaluate` varchar(15) NOT NULL,
  `yearly_inspection_number` int(5) NOT NULL,
  `inspection_area_insp_block_number` int(5) NOT NULL,
  `responsible_inspeciton_area` varchar(5) NOT NULL,
  `remark` varchar(100) NOT NULL,
  PRIMARY KEY (`guid`),
  KEY `line_id` (`line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `admin` (
  `id` varchar(5) NOT NULL COMMENT '管理员用户信息',
  `category` varchar(10) NOT NULL,
  `sys_level` varchar(2) NOT NULL,
  `user_name` varchar(20) NOT NULL,
  `nickname` varchar(20) NOT NULL,
  `user_pwd` varchar(20) NOT NULL,
  `leading_official` varchar(20) DEFAULT NULL,
  `user_job` varchar(5) DEFAULT NULL,
  `phone_number` varchar(11) NOT NULL,
  `birthday` date NOT NULL,
  `user_sex` varchar(2) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `damageinfo` (
  `guid` varchar(40) NOT NULL COMMENT '铁路伤损信息',
  `unit_id` varchar(5) NOT NULL,
  `work_area_id` varchar(5) NOT NULL,
  `line_id` varchar(4) NOT NULL,
  `line_direction` varchar(2) DEFAULT NULL,
  `track_id` varchar(12) DEFAULT NULL,
  `station_id` varchar(7) DEFAULT NULL,
  `turnout_id` varchar(16) DEFAULT NULL,
  `alarm_channel` varchar(20) DEFAULT NULL,
  `station_type` varchar(10) DEFAULT NULL,
  `weld_id` varchar(20) DEFAULT NULL,
  `team_id` varchar(5) NOT NULL,
  `mileage` double(10,5) NOT NULL,
  `left_right_track` varchar(2) NOT NULL,
  `find_time` date NOT NULL,
  `find_person_id` varchar(20) NOT NULL,
  `damage_type` varchar(5) NOT NULL,
  `damage_status` varchar(5) NOT NULL,
  `damage_id` varchar(40) NOT NULL,
  `inspection_car_id` varchar(40) DEFAULT NULL,
  `rail_id` varchar(16) NOT NULL,
  `upload_person_id` varchar(20) DEFAULT NULL,
  `upload_date` date DEFAULT NULL,
  `is_weld_type` varchar(10) DEFAULT NULL,
  `image_path` varchar(40) DEFAULT NULL,
  `weld_type` varchar(5) DEFAULT NULL,
  `is_turnout` varchar(5) DEFAULT NULL,
  `rail_type` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`guid`),
  KEY `work_area_id` (`work_area_id`),
  KEY `line_id` (`line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `ordamageinfo` (
  `guid` varchar(40) NOT NULL COMMENT '铁路伤损信息',
  `unit_id` varchar(5) NOT NULL,
  `work_area_id` varchar(5) NOT NULL,
  `line_id` varchar(4) NOT NULL,
  `line_direction` varchar(2) DEFAULT NULL,
  `track_id` varchar(12) DEFAULT NULL,
  `station_id` varchar(7) DEFAULT NULL,
  `turnout_id` varchar(16) DEFAULT NULL,
  `alarm_channel` varchar(20) DEFAULT NULL,
  `station_type` varchar(10) DEFAULT NULL,
  `weld_id` varchar(20) DEFAULT NULL,
  `team_id` varchar(5) NOT NULL,
  `mileage` double(10,5) NOT NULL,
  `left_right_track` varchar(2) NOT NULL,
  `upload_date` date NOT NULL,
  `find_time` date NOT NULL,
  `upload_person_id` varchar(20) DEFAULT NULL,
  `find_person_id` varchar(20) NOT NULL,
  `damage_type` varchar(5) NOT NULL,
  `damage_status` varchar(5) NOT NULL,
  `damage_id` varchar(40) NOT NULL,
  `inspection_car_id` varchar(40) DEFAULT NULL,
  `rail_id` varchar(16) NOT NULL,
  `image_path` varchar(40) DEFAULT NULL,
  `weld_type` varchar(5) DEFAULT NULL,
  `is_turnout` varchar(5) DEFAULT NULL,
  `is_weld_type` varchar(10) DEFAULT NULL,
  `rail_type` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`guid`),
  KEY `work_area_id` (`work_area_id`),
  KEY `line_id` (`line_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8CREATE TABLE `team` (
  `guid` varchar(40) NOT NULL,
  `team_id` varchar(20) NOT NULL,
  `team_name` varchar(40) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1CREATE TABLE `department` (
  `guid` varchar(40) NOT NULL,
  `department_id` varchar(20) NOT NULL,
  `department_name` varchar(40) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1CREATE TABLE `station` (
  `guid` varchar(40) NOT NULL,
  `station_id` varchar(20) NOT NULL,
  `station_name` varchar(40) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1CREATE TABLE `units` (
  `guid` varchar(40) NOT NULL,
  `unit_id` varchar(20) NOT NULL,
  `unit_name` varchar(40) NOT NULL,
  PRIMARY KEY (`guid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1